import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { eq } from 'drizzle-orm';
import { pgTable, varchar, serial, json, boolean, integer } from "drizzle-orm/pg-core";
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
dotenv.config({ path: '.env' });

const sql = neon(process.env.NEXT_PUBLIC_DATABASE_URL);
const db = drizzle(sql);

// Table 1: Course List
const courseList = pgTable("course_list", {
  id: serial("id").primaryKey(),
  courseId: varchar("course_id").notNull().unique(), // UUID generated by API Phase 1
// ...
});

// Table 2: Course Chapters
const courseChapters = pgTable("course_chapters", {
// ...
  courseId: varchar("course_id").notNull(),
});

async function main() {
    try {
       const rows = await db.select({ id: courseList.courseId }).from(courseList).limit(1);
       if(rows.length > 0) {
           const id = rows[0].id;
           console.log("Testing delete for ID:", id);
           
           await db.delete(courseChapters).where(eq(courseChapters.courseId, id));
           const result = await db.delete(courseList).where(eq(courseList.courseId, id)).returning();
           console.log("Deleted:", result.length > 0 ? "YES" : "NO");
       } else {
           console.log("no courses");
       }
    } catch(e) {
       console.error("error!", e);
    }
}
main();
