import { pgTable, serial, varchar, json, boolean, integer } from "drizzle-orm/pg-core";

// Table 1: Course List
export const courseList = pgTable("course_list", {
  id: serial("id").primaryKey(),
  courseId: varchar("course_id").notNull().unique(), // UUID generated by API Phase 1
  name: varchar("name").notNull(),
  category: varchar("category").notNull(),
  level: varchar("level").notNull(),
  courseOutput: json("course_output").notNull(), // Stores the syllabus layout
  createdBy: varchar("created_by").notNull(), // Clerk User ID or Email
  isPublished: boolean("is_published").default(false).notNull(),
});

// Table 2: Course Chapters
export const courseChapters = pgTable("course_chapters", {
  id: serial("id").primaryKey(),
  courseId: varchar("course_id").notNull(),
  chapterId: integer("chapter_id").notNull(),
  chapterName: varchar("chapter_name").notNull(),
  content: json("content").notNull(), // Stores detailed markdown & code blocks
  videoId: varchar("video_id").notNull(), // YouTube video ID
});
